<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.12" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="VectSharp.PDF" Version="3.2.0" />
    <PackageReference Include="itext7" Version="7.2.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MuPDFCore.MuPDFRenderer\MuPDFCore.MuPDFRenderer.csproj" />
  </ItemGroup>
</Project>
